import { DataSource, Repository } from 'typeorm';
import type { CashMovementFilters, CashMovementRepository, CreateCashMovement, PeriodSummary } from '../../../../application/cash-movement/cash-movement.repository';
import type { CashMovement } from '../../../../domain/cash-movement/cash-movement.types';
import { CashMovementConflictError } from '../../../../domain/cash-movement/cash-movement.errors';
import { CashMovementOrmEntity } from '../entities/cash-movement.orm-entity';
import { FinancialOpeningOrmEntity } from '../entities/financial-opening.orm-entity';
const map = (e: CashMovementOrmEntity): CashMovement => ({ ...e, direction: e.direction as CashMovement['direction'], concept: e.concept as CashMovement['concept'], paymentMethod: { id: e.paymentMethod.id, name: e.paymentMethod.name, isActive: e.paymentMethod.isActive }, createdBy: { id: e.createdBy.id, fullName: e.createdBy.fullName } });
export class CashMovementTypeOrmRepository implements CashMovementRepository {
  constructor(private readonly repository: Repository<CashMovementOrmEntity>, private readonly dataSource: DataSource) {}
  private query(filters: Partial<CashMovementFilters>) { const q = this.repository.createQueryBuilder('m').leftJoinAndSelect('m.paymentMethod', 'pm').leftJoinAndSelect('m.createdBy', 'u'); if (filters.fromDate) q.andWhere('m.movement_date >= :fromDate', { fromDate: filters.fromDate }); if (filters.toDate) q.andWhere('m.movement_date <= :toDate', { toDate: filters.toDate }); if (filters.direction) q.andWhere('m.direction = :direction', { direction: filters.direction }); if (filters.concept) q.andWhere('m.concept = :concept', { concept: filters.concept }); if (filters.paymentMethodId) q.andWhere('m.payment_method_id = :paymentMethodId', { paymentMethodId: filters.paymentMethodId }); if (filters.search) q.andWhere('(m.concept ILIKE :search OR m.observations ILIKE :search OR pm.name ILIKE :search OR u.full_name ILIKE :search)', { search: `%${filters.search}%` }); return q; }
  async list(filters: CashMovementFilters) { const [rows, total] = await this.query(filters).orderBy('m.movementDate', 'DESC').addOrderBy('m.createdAt', 'DESC').skip((filters.page - 1) * filters.pageSize).take(filters.pageSize).getManyAndCount(); return { items: rows.map(map), total }; }
  async summary(filters: Pick<CashMovementFilters, 'fromDate' | 'toDate' | 'direction' | 'concept' | 'paymentMethodId' | 'search'>): Promise<PeriodSummary> { const q = this.query(filters); const raw = await q.select("CAST(COALESCE(SUM(CASE WHEN m.direction = 'INFLOW' THEN m.amount ELSE 0 END), 0) AS numeric(18,2))::text", 'inflows').addSelect("CAST(COALESCE(SUM(CASE WHEN m.direction = 'OUTFLOW' THEN m.amount ELSE 0 END), 0) AS numeric(18,2))::text", 'outflows').addSelect("CAST(COALESCE(SUM(CASE WHEN m.direction = 'INFLOW' THEN m.amount ELSE -m.amount END), 0) AS numeric(18,2))::text", 'net').getRawOne<{ inflows: string; outflows: string; net: string }>(); const aggregate = { inflows: raw?.inflows ?? '0.00', outflows: raw?.outflows ?? '0.00', net: raw?.net ?? '0.00' }; const opening = await this.dataSource.getRepository(FinancialOpeningOrmEntity).findOne({ where: { singletonKey: 'DEFAULT' } }); if (!opening) return { ...aggregate, currentAvailable: null, openingDate: null }; const rawCurrent = await this.dataSource.getRepository(CashMovementOrmEntity).createQueryBuilder('m').select("(CAST(:initial AS numeric) + COALESCE(SUM(CASE WHEN m.direction = 'INFLOW' THEN m.amount ELSE -m.amount END), 0))::text", 'value').setParameter('initial', opening.initialAvailableAmount).getRawOne<{ value: string }>(); return { ...aggregate, currentAvailable: rawCurrent?.value ?? opening.initialAvailableAmount, openingDate: opening.openingDate }; }
  async findById(id: string) { const e = await this.query({}).andWhere('m.id = :id', { id }).getOne(); return e ? map(e) : null; }
  async findByIdempotencyKey(key: string) { const e = await this.query({}).andWhere('m.idempotency_key = :key', { key }).getOne(); return e ? map(e) : null; }
  async create(input: CreateCashMovement) { const saved = await this.repository.save(this.repository.create(input)); const e = await this.findById(saved.id); if (!e) throw new Error('No fue posible recuperar el movimiento.'); return e; }
  async reverse(original: CashMovement, input: CreateCashMovement) { return this.dataSource.transaction(async (manager) => { const existing = await manager.getRepository(CashMovementOrmEntity).findOne({ where: { reversedMovementId: original.id } }); if (existing) throw new CashMovementConflictError('El movimiento ya fue reversado.'); try { const saved = await manager.getRepository(CashMovementOrmEntity).save(manager.getRepository(CashMovementOrmEntity).create(input)); return map(await manager.getRepository(CashMovementOrmEntity).findOneOrFail({ where: { id: saved.id }, relations: { paymentMethod: true, createdBy: true } })); } catch (error) { if ((error as { code?: string }).code === '23505') throw new CashMovementConflictError('El movimiento ya fue reversado.'); throw error; } }); }
}
