import { Repository } from 'typeorm';
import type { Collector, EligibleCollectorUser } from '../../../../domain/collector/collector.types';
import type { CollectorCreate, CollectorListQuery, CollectorRepository, CollectorUpdate } from '../../../../application/collector/collector.repository';
import { CollectorOrmEntity } from '../entities/collector.orm-entity';
import { UserOrmEntity } from '../entities/user.orm-entity';

export const mapCollector = (row: CollectorOrmEntity): Collector => ({ id: row.id, identification: row.identification, firstName: row.firstName, firstLastName: row.firstLastName, ...(row.secondLastName ? { secondLastName: row.secondLastName } : {}), phone: row.phone, ...(row.alternativePhone ? { alternativePhone: row.alternativePhone } : {}), ...(row.email ? { email: row.email } : {}), birthDate: row.birthDate, address: row.address, photoFileKey: row.photoFileKey, userId: row.userId, user: row.user ? { fullName: row.user.fullName, username: row.user.username } : null, isActive: row.isActive, createdAt: row.createdAt, updatedAt: row.updatedAt });

export class CollectorTypeOrmRepository implements CollectorRepository {
  constructor(private readonly collectors: Repository<CollectorOrmEntity>, private readonly users: Repository<UserOrmEntity>) {}
   async list(query: CollectorListQuery) { const qb = this.collectors.createQueryBuilder('c').leftJoin('c.user', 'u').addSelect(['u.id', 'u.fullName', 'u.username']).orderBy('c.firstLastName', 'ASC').addOrderBy('c.firstName', 'ASC'); if (query.status !== 'ALL') qb.andWhere('c.is_active = :active', { active: query.status === 'ACTIVE' }); if (query.search?.trim()) { const search = `%${query.search.trim().toUpperCase()}%`; qb.andWhere('(upper(c.identification) LIKE :search OR upper(c.first_name) LIKE :search OR upper(c.first_last_name) LIKE :search OR upper(coalesce(c.second_last_name, \'\')) LIKE :search OR upper(c.phone) LIKE :search OR upper(coalesce(c.alternative_phone, \'\')) LIKE :search OR lower(coalesce(c.email, \'\')) LIKE lower(:search) OR upper(c.address) LIKE :search)', { search }); } const [rows, total] = await qb.skip((query.page - 1) * query.pageSize).take(query.pageSize).getManyAndCount(); return { items: rows.map(mapCollector), total }; }
   async findById(id: string) { const row = await this.collectors.createQueryBuilder('c').leftJoin('c.user', 'u').addSelect(['u.id', 'u.fullName', 'u.username']).where('c.id = :id', { id }).getOne(); return row ? mapCollector(row) : null; }
  async identificationExists(identification: string, exceptId?: string) { const qb = this.collectors.createQueryBuilder('c').where('lower(c.identification) = lower(:identification)', { identification }); if (exceptId) qb.andWhere('c.id <> :exceptId', { exceptId }); return Boolean(await qb.getOne()); }
   async create(input: CollectorCreate) { return mapCollector(await this.collectors.save(this.collectors.create({ ...input, isActive: true, secondLastName: input.secondLastName ?? null, alternativePhone: input.alternativePhone ?? null, email: input.email ?? null, photoFileKey: input.photoFileKey ?? null, userId: input.userId ?? null }))); }
  async update(id: string, input: CollectorUpdate) { const patch: Record<string, unknown> = { ...input }; for (const field of ['secondLastName', 'alternativePhone', 'email'] as const) if (Object.prototype.hasOwnProperty.call(input, field)) patch[field] = input[field] ?? null; const result = await this.collectors.update(id, patch); if (!result.affected) return null; return this.findById(id); }
  async updateStatus(id: string, isActive: boolean) { const result = await this.collectors.update(id, { isActive }); if (!result.affected) return null; return this.findById(id); }
  async updateUser(id: string, userId: string | null) { const result = await this.collectors.update(id, { userId }); if (!result.affected) return null; return this.findById(id); }
  async findEligibleUser(id: string): Promise<EligibleCollectorUser | null> { const row = await this.users.createQueryBuilder('u').innerJoin('u.role', 'r').select(['u.id', 'u.fullName', 'u.username']).where('u.id = :id AND u.is_active = true AND r.code = :role AND r.is_active = true', { id, role: 'COLLECTOR' }).getOne(); return row ? { id: row.id, fullName: row.fullName, username: row.username } : null; }
  async userLinkedToAnother(userId: string, collectorId: string) { const qb = this.collectors.createQueryBuilder('c').where('c.user_id = :userId', { userId }); if (collectorId) qb.andWhere('c.id <> :collectorId', { collectorId }); return Boolean(await qb.getOne()); }
   async listEligibleUsers() { const rows = await this.users.createQueryBuilder('u').innerJoin('u.role', 'r').leftJoin(CollectorOrmEntity, 'c', 'c.user_id = u.id').select(['u.id', 'u.fullName', 'u.username']).where('u.is_active = true AND r.code = :role AND r.is_active = true AND c.id IS NULL', { role: 'COLLECTOR' }).orderBy('u.fullName', 'ASC').getMany(); return rows.map((row) => ({ id: row.id, fullName: row.fullName, username: row.username })); }
}
