import { InjectRepository } from '@nestjs/typeorm';
import { Injectable } from '@nestjs/common';
import { DataSource, In, Repository } from 'typeorm';
import { SecurityRole, SecuritySession, SecurityUser } from '../../../../domain/security/security.types';
import { SecurityRepository } from '../../../../application/security/security.ports';
import { PermissionOrmEntity, RoleOrmEntity, RolePermissionOrmEntity, UserOrmEntity, UserSessionOrmEntity } from '../entities';

const role = (value: RoleOrmEntity): SecurityRole => ({ id: value.id, code: value.code, name: value.name, description: value.description, isSystem: value.isSystem, isSuperAdmin: value.isSuperAdmin, isActive: value.isActive, createdAt: value.createdAt, updatedAt: value.updatedAt });
const user = (value: UserOrmEntity): SecurityUser => ({ id: value.id, username: value.username, fullName: value.fullName, passwordHash: value.passwordHash, roleId: value.roleId, role: role(value.role), isActive: value.isActive, lastLoginAt: value.lastLoginAt, createdAt: value.createdAt, updatedAt: value.updatedAt });
@Injectable()
export class SecurityTypeOrmRepository implements SecurityRepository {
  constructor(@InjectRepository(UserOrmEntity) private readonly users: Repository<UserOrmEntity>, @InjectRepository(RoleOrmEntity) private readonly roles: Repository<RoleOrmEntity>, @InjectRepository(PermissionOrmEntity) private readonly permissions: Repository<PermissionOrmEntity>, @InjectRepository(RolePermissionOrmEntity) private readonly rolePermissions: Repository<RolePermissionOrmEntity>, @InjectRepository(UserSessionOrmEntity) private readonly sessions: Repository<UserSessionOrmEntity>, private readonly dataSource: DataSource) {}
  async findUserByUsername(username: string) { const value = await this.users.createQueryBuilder('u').addSelect('u.passwordHash').leftJoinAndSelect('u.role', 'role').where('lower(u.username) = :username', { username }).getOne(); return value ? user(value) : null; }
  async findUserById(id: string) { const value = await this.users.createQueryBuilder('u').addSelect('u.passwordHash').leftJoinAndSelect('u.role', 'role').where('u.id = :id', { id }).getOne(); return value ? user(value) : null; }
  async listUsers(filter: { search?: string; status?: string; roleId?: string; page: number; pageSize: number }) { const qb = this.users.createQueryBuilder('u').leftJoinAndSelect('u.role', 'role').orderBy('u.username', 'ASC'); if (filter.search) qb.andWhere('(lower(u.username) LIKE :search OR upper(u.full_name) LIKE :search)', { search: `%${filter.search.trim().toUpperCase()}%` }); if (filter.status === 'ACTIVE') qb.andWhere('u.is_active = true'); if (filter.status === 'INACTIVE') qb.andWhere('u.is_active = false'); if (filter.roleId) qb.andWhere('u.role_id = :roleId', { roleId: filter.roleId }); const [items, total] = await qb.skip((filter.page - 1) * filter.pageSize).take(filter.pageSize).getManyAndCount(); return { items: items.map(user), total }; }
  async usernameExists(username: string, exceptId?: string) { const qb = this.users.createQueryBuilder('u').where('lower(u.username) = :username', { username: username.trim().toLowerCase() }); if (exceptId) qb.andWhere('u.id <> :exceptId', { exceptId }); return Boolean(await qb.getOne()); }
  async saveUser(input: Partial<SecurityUser> & { id?: string }) { const entity = this.users.create({ id: input.id, username: input.username, fullName: input.fullName, passwordHash: input.passwordHash, roleId: input.roleId, isActive: input.isActive, lastLoginAt: input.lastLoginAt }); const saved = await this.users.save(entity); return (await this.findUserById(saved.id))!; }
  async findActiveRole(id: string) { const value = await this.roles.findOneBy({ id, isActive: true }); return value ? role(value) : null; }
  async listRoles() { return (await this.roles.find({ order: { name: 'ASC' } })).map(role); }
  async listPermissions() { return (await this.permissions.find({ order: { module: 'ASC', code: 'ASC' } })).map((value) => ({ id: value.id, code: value.code, name: value.name, module: value.module, description: value.description, createdAt: value.createdAt, updatedAt: value.updatedAt })); }
  async rolePermissionCodes(roleId: string) { const rows = await this.rolePermissions.find({ where: { roleId }, relations: { permission: true } }); return rows.map((row) => row.permission.code); }
  async findPermissionsByCodes(codes: string[]) { return (await this.permissions.find({ where: { code: In(codes) } })).map((value) => ({ id: value.id, code: value.code, name: value.name, module: value.module, description: value.description, createdAt: value.createdAt, updatedAt: value.updatedAt })); }
  async replaceRolePermissions(roleId: string, permissionIds: string[]) { await this.dataSource.transaction(async (manager) => { await manager.delete(RolePermissionOrmEntity, { roleId }); await manager.insert(RolePermissionOrmEntity, permissionIds.map((permissionId) => ({ roleId, permissionId }))); }); }
  async findSessionByHash(tokenHash: string) { const value = await this.sessions.findOneBy({ tokenHash }); return value ? { id: value.id, userId: value.userId, tokenHash: value.tokenHash, expiresAt: value.expiresAt, revokedAt: value.revokedAt, createdAt: value.createdAt } : null; }
  async saveSession(input: Omit<SecuritySession, 'id' | 'createdAt'>) { const saved = await this.sessions.save(this.sessions.create(input)); return { id: saved.id, userId: saved.userId, tokenHash: saved.tokenHash, expiresAt: saved.expiresAt, revokedAt: saved.revokedAt, createdAt: saved.createdAt }; }
  async revokeSession(id: string) { await this.sessions.update(id, { revokedAt: new Date() }); }
  async revokeOtherSessions(userId: string, exceptSessionId: string) { await this.sessions.createQueryBuilder().update().set({ revokedAt: new Date() }).where('user_id = :userId AND id <> :exceptSessionId AND revoked_at IS NULL', { userId, exceptSessionId }).execute(); }
  async revokeUserSessions(userId: string) { await this.sessions.createQueryBuilder().update().set({ revokedAt: new Date() }).where('user_id = :userId AND revoked_at IS NULL', { userId }).execute(); }
  countActiveSuperAdmins() { return this.users.createQueryBuilder('u').innerJoin('u.role', 'r').where('u.is_active = true AND r.is_super_admin = true AND r.is_active = true').getCount(); }
}
