import { CashMovementConflictError, CashMovementValidationError } from '../src/domain/cash-movement/cash-movement.errors';
import { directionForManualConcept, RecordManualCashMovementUseCase, ReverseCashMovementUseCase } from '../src/application/cash-movement/cash-movement.use-cases';
import type { CashMovementRepository } from '../src/application/cash-movement/cash-movement.repository';
import type { CashMovement } from '../src/domain/cash-movement/cash-movement.types';

const movement = (fingerprint: string): CashMovement => ({ id: '1', direction: 'INFLOW', concept: 'CAPITAL_CONTRIBUTION', amount: '10.00', movementDate: '2026-01-01', paymentMethodId: 'pm', observations: null, reversedMovementId: null, createdByUserId: 'actor', idempotencyKey: 'same', idempotencyFingerprint: fingerprint, createdAt: new Date(), paymentMethod: { id: 'pm', name: 'Cash', isActive: true }, createdBy: { id: 'actor', fullName: 'Actor' } });
describe('cash movement application rules', () => {
  it('derives direction and rejects reserved concepts', () => { expect(directionForManualConcept('CAPITAL_CONTRIBUTION')).toBe('INFLOW'); expect(directionForManualConcept('OPERATING_EXPENSE')).toBe('OUTFLOW'); expect(() => directionForManualConcept('LOAN_DISBURSEMENT')).toThrow(CashMovementValidationError); });
  it('requires an opening and uses the actor supplied by the application', async () => { const repository = { findByIdempotencyKey: jest.fn(), create: jest.fn() } as unknown as CashMovementRepository; const useCase = new RecordManualCashMovementUseCase(repository, { find: async () => null }, { findById: async () => ({ isActive: true }) }); await expect(useCase.execute({ concept: 'CAPITAL_CONTRIBUTION', amount: '10', movementDate: '2026-01-01', paymentMethodId: 'pm' }, 'actor')).rejects.toThrow('Debe realizar la apertura financiera antes de registrar movimientos.'); });
  it('returns an identical idempotent movement and rejects a different fingerprint', async () => { const repository = { findByIdempotencyKey: jest.fn().mockResolvedValue(movement('different')), create: jest.fn() } as unknown as CashMovementRepository; const useCase = new RecordManualCashMovementUseCase(repository, { find: async () => ({ openingDate: '2025-01-01' }) }, { findById: async () => ({ isActive: true }) }); await expect(useCase.execute({ concept: 'CAPITAL_CONTRIBUTION', amount: '10', movementDate: '2026-01-01', paymentMethodId: 'pm', idempotencyKey: 'same' }, 'actor')).rejects.toThrow(CashMovementConflictError); });
  it('rejects reversal chains', async () => { const original = { ...movement('fingerprint'), concept: 'REVERSAL' as const }; const repository = { findById: jest.fn().mockResolvedValue(original), reverse: jest.fn() } as unknown as CashMovementRepository; const useCase = new ReverseCashMovementUseCase(repository, { find: async () => ({ openingDate: '2025-01-01' }) }); await expect(useCase.execute(original.id, { movementDate: '2026-01-02', reason: 'Duplicate correction' }, 'actor')).rejects.toThrow(CashMovementValidationError); });
  it('rejects impossible calendar dates for creation and reversal', async () => { const repository = { findById: jest.fn().mockResolvedValue(movement('fingerprint')), create: jest.fn(), reverse: jest.fn() } as unknown as CashMovementRepository; const opening = { find: async () => ({ openingDate: '2025-01-01' }) }; const create = new RecordManualCashMovementUseCase(repository, opening, { findById: async () => ({ isActive: true }) }); await expect(create.execute({ concept: 'CAPITAL_CONTRIBUTION', amount: '10', movementDate: '2026-02-30', paymentMethodId: 'pm' }, 'actor')).rejects.toThrow('La fecha del movimiento no es válida.'); const reverse = new ReverseCashMovementUseCase(repository, opening); await expect(reverse.execute('1', { movementDate: '2026-02-30', reason: 'Correction' }, 'actor')).rejects.toThrow('La fecha del movimiento no es válida.'); });
});
