import type { ReactElement } from 'react';
import { useEffect, useMemo, useState } from 'react';
import { territorialUseCases } from '../../app/territorial';
import type { Canton, District, Province } from '../../domain/entities/territorial';
import { CatalogStates, SearchField } from '../components/catalog/CatalogStates';

export function CantonsPage(): ReactElement {
  const [cantons, setCantons] = useState<Canton[]>([]); const [districts, setDistricts] = useState<District[]>([]); const [provinces, setProvinces] = useState<Province[]>([]); const [search, setSearch] = useState(''); const [provinceCode, setProvinceCode] = useState(''); const [selected, setSelected] = useState<Canton | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let ignore = false; Promise.all([territorialUseCases.listCantons.execute(), territorialUseCases.listDistricts.execute(), territorialUseCases.listProvinces.execute()]).then(([items, related, parentItems]) => { if (!ignore) { setCantons(items); setDistricts(related); setProvinces(parentItems); setLoading(false); } }).catch((reason: unknown) => { if (!ignore) { setError(reason instanceof Error ? reason.message : 'No se pudo cargar la información.'); setLoading(false); } }); return () => { ignore = true; }; }, []);
  const filtered = useMemo(() => cantons.filter((item) => (provinceCode === '' || item.province.code === Number(provinceCode)) && `${item.code} ${item.name}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [cantons, provinceCode, search]);
  const selectedDistricts = selected ? districts.filter((item) => item.canton.code === selected.code) : [];
   return <section className="catalog-page" aria-labelledby="page-title"><div className="catalog-heading"><div><h2 id="page-title">Cantones</h2><p>Cantones por provincia</p></div><span className="catalog-count">{filtered.length} de {cantons.length}</span></div><div className="catalog-toolbar"><SearchField value={search} onChange={setSearch} /><label className="catalog-search">Provincia<select value={provinceCode} onChange={(event) => setProvinceCode(event.target.value)}><option value="">Todas las provincias</option>{provinces.map((province) => <option key={province.code} value={province.code}>{province.name}</option>)}</select></label></div><CatalogStates loading={loading} error={error} empty={!loading && !error && filtered.length === 0} />{!loading && !error && filtered.length > 0 && <div className="catalog-layout"><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Código</th><th>Cantón</th><th>Provincia</th><th>Distritos</th></tr></thead><tbody>{filtered.map((canton) => <tr key={canton.code} className={selected?.code === canton.code ? 'catalog-row--selected' : ''} onClick={() => setSelected(canton)}><td>{canton.code}</td><td>{canton.name}</td><td>{canton.province.name}</td><td>{districts.filter((district) => district.canton.code === canton.code).length}</td></tr>)}</tbody></table></div>{selected && <aside className="catalog-detail"><h3>{selected.name}</h3><p>{selected.province.name} · {selectedDistricts.length} distritos</p><ul>{selectedDistricts.map((district) => <li key={district.code}><strong>{district.code}</strong> {district.name}</li>)}</ul></aside>}</div>}</section>;
}
