import { useEffect, useState, type ReactElement } from 'react';
import { collectorUseCases } from '../../app/collectors';
import type { Collector, EligibleCollectorUser } from '../../domain/entities/collector';
import type { CollectorInput, CollectorUpdateInput } from '../../application/ports/collector.repository';
import { CompactImageUploader } from '../components/CompactImageUploader';
import { useAuth } from '../hooks/auth-context';
import { collectorUserLabel } from '../helpers/collector-user-label';

type Form = Omit<CollectorInput, 'photo' | 'userId'> & { userId: string; photo?: File };
const emptyForm: Form = { identification: '', firstName: '', firstLastName: '', secondLastName: '', phone: '', alternativePhone: '', email: '', birthDate: '', address: '', userId: '' };
type Modal = 'create' | 'edit' | 'user' | 'status' | null;

export function CollectorsPage(): ReactElement {
  const { can } = useAuth();
  const [items, setItems] = useState<Collector[]>([]); const [total, setTotal] = useState(0); const [query, setQuery] = useState({ search: '', status: 'ACTIVE' as 'ACTIVE' | 'INACTIVE' | 'ALL', page: 1, pageSize: 10 as 10 | 20 | 50 });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState<Modal>(null); const [selected, setSelected] = useState<Collector>(); const [form, setForm] = useState<Form>(emptyForm); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState(''); const [users, setUsers] = useState<EligibleCollectorUser[]>([]); const [photoUrl, setPhotoUrl] = useState('');

  const load = async () => { setLoading(true); setError(''); try { const result = await collectorUseCases.list.execute(query); setItems(result.items); setTotal(result.total); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudieron cargar los cobradores.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [query.status, query.page, query.pageSize]);
  const update = (patch: Partial<Form>) => setForm((current) => ({ ...current, ...patch }));
  const openCreate = async () => { if (!can('collectors.create')) return; setSelected(undefined); setForm({ ...emptyForm }); setFormError(''); if (can('collectors.user.assign')) { try { setUsers(await collectorUseCases.eligibleUsers.execute()); } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'No se pudieron cargar los usuarios elegibles.'); } } setModal('create'); };
  const openEdit = async (item: Collector) => { if (!can('collectors.update')) return; setFormError(''); try { const value = await collectorUseCases.get.execute(item.id); setSelected(value); setForm({ identification: value.identification, firstName: value.firstName, firstLastName: value.firstLastName, secondLastName: value.secondLastName ?? '', phone: value.phone, alternativePhone: value.alternativePhone ?? '', email: value.email ?? '', birthDate: value.birthDate, address: value.address, userId: '' }); setModal('edit'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar el cobrador.'); } };
  const save = async () => { if (!modal || modal === 'status' || modal === 'user') return; if (!form.identification || !form.firstName || !form.firstLastName || !form.phone || !form.birthDate || !form.address || (form.email && !/^\S+@\S+\.\S+$/.test(form.email))) { setFormError('Completá los campos requeridos y verificá el correo electrónico.'); return; } setSaving(true); setFormError(''); try { if (modal === 'create') await collectorUseCases.create.execute({ ...form, userId: form.userId || null }); else if (selected) { const editable: CollectorUpdateInput = { identification: form.identification, firstName: form.firstName, firstLastName: form.firstLastName, secondLastName: form.secondLastName, phone: form.phone, alternativePhone: form.alternativePhone, email: form.email, birthDate: form.birthDate, address: form.address, photo: form.photo }; await collectorUseCases.update.execute(selected.id, editable); } setModal(null); await load(); } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'No fue posible guardar el cobrador.'); } finally { setSaving(false); } };
  const openUsers = async (item: Collector) => { if (!can('collectors.user.assign')) return; setSelected(item); setFormError(''); try { setUsers(await collectorUseCases.eligibleUsers.execute()); setModal('user'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudieron cargar los usuarios elegibles.'); } };
  const linkUser = async (userId: string) => { if (!selected) return; setSaving(true); setFormError(''); try { await collectorUseCases.linkUser.execute(selected.id, userId || null); setModal(null); await load(); } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'No fue posible actualizar el vínculo.'); } finally { setSaving(false); } };
  const changeStatus = async () => { if (!selected) return; setSaving(true); try { await collectorUseCases.changeStatus.execute(selected.id, !selected.isActive); setModal(null); await load(); } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'No fue posible actualizar el estado.'); } finally { setSaving(false); } };
  const viewPhoto = async (item: Collector) => { try { const blob = await collectorUseCases.photo.execute(item.id); setPhotoUrl(URL.createObjectURL(blob)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar la fotografía.'); } };

  return <section className="collector-admin"><div className="payment-heading"><div><p className="eyebrow">GESTIÓN</p><h2>Cobradores</h2></div>{can('collectors.create') && <button className="button button--primary" type="button" onClick={openCreate}>Nuevo cobrador</button>}</div>
    <div className="payment-toolbar"><label>Buscar<input value={query.search} onChange={(event) => setQuery({ ...query, search: event.target.value, page: 1 })} onKeyDown={(event) => { if (event.key === 'Enter') void load(); }} placeholder="Identificación, nombre o teléfono" /></label><label>Estado<select value={query.status} onChange={(event) => setQuery({ ...query, status: event.target.value as typeof query.status, page: 1 })}><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option><option value="ALL">Todos</option></select></label><button className="button button--secondary" type="button" onClick={() => void load()}>Buscar</button></div>
    {error && <div className="catalog-message catalog-message--error" role="alert">{error}</div>}{loading ? <div className="catalog-message">Cargando cobradores…</div> : !items.length ? <div className="catalog-message">No se encontraron cobradores.</div> : <div className="catalog-table-wrap"><table className="catalog-table collector-table"><thead><tr><th>Identificación</th><th>Cobrador</th><th>Teléfono</th><th>Usuario</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.identification}</td><td>{item.firstName} {item.firstLastName} {item.secondLastName ?? ''}</td><td>{item.phone}</td><td>{collectorUserLabel(item)}</td><td><span className={`status-badge ${item.isActive ? 'status-badge--active' : 'status-badge--inactive'}`}>{item.isActive ? 'Activo' : 'Inactivo'}</span></td><td><div className="row-actions">{can('collectors.update') && <button type="button" onClick={() => void openEdit(item)}>Editar</button>}{can('collectors.user.assign') && <button type="button" onClick={() => void openUsers(item)}>{item.userId ? 'Usuario' : 'Vincular'}</button>}{can('collectors.status.change') && <button type="button" onClick={() => { setSelected(item); setFormError(''); setModal('status'); }}>{item.isActive ? 'Inactivar' : 'Activar'}</button>}{can('collectors.photo.view') && item.photoFileKey && <button type="button" onClick={() => void viewPhoto(item)}>Foto</button>}</div></td></tr>)}</tbody></table></div>}
    <div className="security-pagination"><button className="button button--secondary" disabled={query.page <= 1} onClick={() => setQuery({ ...query, page: query.page - 1 })}>Anterior</button><span>Página {query.page} · {total} cobradores</span><label>Mostrar<select value={query.pageSize} onChange={(event) => setQuery({ ...query, page: 1, pageSize: Number(event.target.value) as 10 | 20 | 50 })}><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></label><button className="button button--secondary" disabled={query.page * query.pageSize >= total} onClick={() => setQuery({ ...query, page: query.page + 1 })}>Siguiente</button></div>
    {modal && <CollectorDialog modal={modal} selected={selected} form={form} update={update} users={users} allowUser={can('collectors.user.assign')} saving={saving} error={formError} close={() => setModal(null)} save={modal === 'status' ? changeStatus : modal === 'user' ? () => void linkUser(form.userId) : save} />}{photoUrl && <button className="image-modal" type="button" onClick={() => { URL.revokeObjectURL(photoUrl); setPhotoUrl(''); }}><img src={photoUrl} alt="Foto del cobrador" /></button>}</section>;
}

function CollectorDialog({ modal, selected, form, update, users, allowUser, saving, error, close, save }: { modal: Exclude<Modal, null>; selected?: Collector; form: Form; update: (patch: Partial<Form>) => void; users: EligibleCollectorUser[]; allowUser: boolean; saving: boolean; error: string; close: () => void; save: () => void }): ReactElement {
  if (modal === 'status') return <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true"><h3>{selected?.isActive ? 'Inactivar cobrador' : 'Activar cobrador'}</h3><p>¿Confirmás cambiar el estado de <strong>{selected?.firstName} {selected?.firstLastName}</strong>?</p>{error && <p className="form-error">{error}</p>}<DialogActions saving={saving} close={close} save={save} /></div></div>;
  if (modal === 'user') return <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true"><h3>Vincular usuario</h3><label>Usuario<select value={form.userId} onChange={(event) => update({ userId: event.target.value })}><option value="">Sin vincular</option>{users.map((user) => <option key={user.id} value={user.id}>{user.fullName} · {user.username}</option>)}</select></label>{error && <p className="form-error">{error}</p>}<DialogActions saving={saving} close={close} save={save} /></div></div>;
  return <div className="dialog-backdrop"><div className="dialog collector-dialog" role="dialog" aria-modal="true"><h3>{modal === 'create' ? 'Nuevo cobrador' : 'Editar cobrador'}</h3>{error && <p className="form-error">{error}</p>}<div className="collector-form">{[['identification','Identificación'],['firstName','Nombre'],['firstLastName','Primer apellido'],['secondLastName','Segundo apellido'],['phone','Teléfono'],['alternativePhone','Teléfono alternativo'],['email','Correo electrónico'],['birthDate','Fecha de nacimiento'],['address','Dirección']].map(([key, label]) => <label key={key}>{label}<input type={key === 'birthDate' ? 'date' : key === 'email' ? 'email' : 'text'} value={String(form[key as keyof Form] ?? '')} onChange={(event) => update({ [key]: event.target.value })} required={['identification','firstName','firstLastName','phone','birthDate','address'].includes(key)} /></label>)}{modal === 'create' && allowUser && <label>Usuario<select value={form.userId} onChange={(event) => update({ userId: event.target.value })}><option value="">Sin vincular</option>{users.map((user) => <option key={user.id} value={user.id}>{user.fullName} · {user.username}</option>)}</select></label>}<CompactImageUploader label="Foto del cobrador (opcional)" file={form.photo} onChange={(photo) => update({ photo })} /></div><DialogActions saving={saving} close={close} save={save} /></div></div>;
}
function DialogActions({ saving, close, save }: { saving: boolean; close: () => void; save: () => void }): ReactElement { return <div className="dialog-actions"><button className="button button--secondary" type="button" onClick={close}>Cancelar</button><button className="button button--primary" type="button" disabled={saving} onClick={save}>{saving ? 'Guardando…' : 'Confirmar'}</button></div>; }
