import { useEffect, useState, type ReactElement } from 'react';
import { Link, useParams } from 'react-router-dom';
import { customerUseCases } from '../../app/customers';
import type { CustomerDetail } from '../../domain/entities/customer';
import { generateCustomerFileReport } from '../../infrastructure/reports/customer-file-report.service';
import { useAuth } from '../hooks/auth-context';
import { formatNationality } from '../formatters/nationality';

export function CustomerDetailPage(): ReactElement {
  const { id = '' } = useParams(); const { can } = useAuth();
  const [item, setItem] = useState<CustomerDetail>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [images, setImages] = useState<{ identification?: string; property?: string }>({}); const [preview, setPreview] = useState('');
  const fetchFile = async (customerId: string, kind: 'identification' | 'property') => { if (!can('customers.files.view')) throw new Error('No tienes permiso para acceder a los archivos del cliente.'); return customerUseCases.file.execute(customerId, kind); };
  const loadImage = async (customerId: string, kind: 'identification' | 'property') => URL.createObjectURL(await fetchFile(customerId, kind));
  useEffect(() => { let active = true; void customerUseCases.get.execute(id).then((detail) => { if (active) setItem(detail); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'No se pudo cargar el cliente.')).finally(() => setLoading(false)); return () => { active = false; }; }, [id]);
  useEffect(() => { if (!can('customers.files.view')) return; let active = true; void Promise.allSettled([loadImage(id, 'identification'), loadImage(id, 'property')]).then(([identification, property]) => { if (!active) return; setImages({ identification: identification.status === 'fulfilled' ? identification.value : undefined, property: property.status === 'fulfilled' ? property.value : undefined }); }); return () => { active = false; }; }, [id, can]);
  useEffect(() => () => { Object.values(images).forEach((url) => { if (url) URL.revokeObjectURL(url); }); }, [images]);
  if (loading) return <div className="catalog-message">Cargando cliente…</div>; if (error || !item) return <div className="catalog-message catalog-message--error">{error || 'Cliente no encontrado.'}</div>;
  const c = item.customer; const a = item.address; const hierarchy = `${item.district.name} · ${item.district.canton.name} · ${item.district.canton.province.name}`;
  return <section className="customer-detail-page"><div className="customer-admin__heading"><div><p className="eyebrow">GESTIÓN / CLIENTES</p><h2>{c.firstName} {c.firstLastName}</h2><p className="muted">{c.identification}</p></div><div className="payment-actions">{can('customers.export') && <button className="button button--secondary" onClick={() => void generateCustomerFileReport(item, fetchFile)}>Descargar expediente</button>}{can('customers.update') && <Link className="button button--primary" to={`/customers/${id}/edit`}>Editar</Link>}</div></div><div className="customer-detail-grid"><Info title="Datos personales" rows={['Identificación', c.identification, 'Género', c.gender === 'MALE' ? 'Masculino' : 'Femenino', 'Nacimiento', c.birthDate, 'Nacionalidad', formatNationality(c.nationality, c.otherNationality)]} /><Info title="Contacto" rows={['Teléfono principal', c.primaryPhone, 'Teléfono secundario', c.secondaryPhone || '—', 'Correo', c.email || '—']} /><Info title="Dirección y ubicación" rows={['Jerarquía', hierarchy, 'Dirección exacta', a.exactAddress, 'Coordenadas', a.latitude === undefined ? '—' : `${a.latitude}, ${a.longitude}`]} /><Info title="Estado y observaciones" rows={['Estado', c.isActive ? 'Activo' : 'Inactivo', 'Observaciones', c.observations || '—']} /></div>{can('customers.files.view') && <section className="customer-documents"><h3>Documentos</h3><div className="customer-images">{images.identification && <Doc src={images.identification} label="Identificación frontal" onPreview={setPreview} />}{images.property && <Doc src={images.property} label="Foto de casa o negocio" onPreview={setPreview} />}</div></section>}{preview && <button className="image-modal" type="button" aria-label="Cerrar vista previa" onClick={() => setPreview('')}><img src={preview} alt="Vista previa del documento" /></button>}</section>;
}
function Info({ title, rows }: { title: string; rows: string[] }): ReactElement { const pairs = []; for (let index = 0; index < rows.length; index += 2) pairs.push(<p key={rows[index]}><strong>{rows[index]}</strong><span>{rows[index + 1]}</span></p>); return <article className="customer-info-card"><h3>{title}</h3>{pairs}</article>; }
function Doc({ src, label, onPreview }: { src: string; label: string; onPreview: (value: string) => void }): ReactElement { return <figure><img src={src} alt={label} onClick={() => onPreview(src)} /><figcaption>{label}</figcaption></figure>; }
