import type { ReactElement } from 'react';
import { useEffect, useMemo, useState } from 'react';
import { territorialUseCases } from '../../app/territorial';
import type { Canton, District, Province } from '../../domain/entities/territorial';
import { CatalogStates, SearchField } from '../components/catalog/CatalogStates';

export function DistrictsPage(): ReactElement {
  const [districts, setDistricts] = useState<District[]>([]); const [cantons, setCantons] = useState<Canton[]>([]); const [provinces, setProvinces] = useState<Province[]>([]); const [search, setSearch] = useState(''); const [provinceCode, setProvinceCode] = useState(''); const [cantonCode, setCantonCode] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let ignore = false; Promise.all([territorialUseCases.listDistricts.execute(), territorialUseCases.listCantons.execute(), territorialUseCases.listProvinces.execute()]).then(([items, parentItems, provinceItems]) => { if (!ignore) { setDistricts(items); setCantons(parentItems); setProvinces(provinceItems); setLoading(false); } }).catch((reason: unknown) => { if (!ignore) { setError(reason instanceof Error ? reason.message : 'No se pudo cargar la información.'); setLoading(false); } }); return () => { ignore = true; }; }, []);
  const filteredCantons = cantons.filter((canton) => provinceCode === '' || canton.province.code === Number(provinceCode));
  const filtered = useMemo(() => districts.filter((item) => (provinceCode === '' || item.province.code === Number(provinceCode)) && (cantonCode === '' || item.canton.code === Number(cantonCode)) && `${item.code} ${item.name}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [districts, provinceCode, cantonCode, search]);
   return <section className="catalog-page" aria-labelledby="page-title"><div className="catalog-heading"><div><h2 id="page-title">Distritos</h2><p>Distritos por cantón y provincia</p></div><span className="catalog-count">{filtered.length} de {districts.length}</span></div><div className="catalog-toolbar"><SearchField value={search} onChange={setSearch} /><label className="catalog-search">Provincia<select value={provinceCode} onChange={(event) => { setProvinceCode(event.target.value); setCantonCode(''); }}><option value="">Todas las provincias</option>{provinces.map((province) => <option key={province.code} value={province.code}>{province.name}</option>)}</select></label><label className="catalog-search">Cantón<select value={cantonCode} onChange={(event) => setCantonCode(event.target.value)} disabled={filteredCantons.length === 0}><option value="">Todos los cantones</option>{filteredCantons.map((canton) => <option key={canton.code} value={canton.code}>{canton.name}</option>)}</select></label></div><CatalogStates loading={loading} error={error} empty={!loading && !error && filtered.length === 0} />{!loading && !error && filtered.length > 0 && <div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Código</th><th>Distrito</th><th>Cantón</th><th>Provincia</th></tr></thead><tbody>{filtered.map((district) => <tr key={district.code}><td>{district.code}</td><td>{district.name}</td><td>{district.canton.name}</td><td>{district.province.name}</td></tr>)}</tbody></table></div>}</section>;
}
