import { useEffect, useState, type ReactElement } from 'react';
import { financialOpeningUseCases } from '../../app/financial-opening';
import type { FinancialOpening, FinancialOpeningResponse } from '../../domain/entities/financial-opening';
import { canPerformOpening, financialOpeningConfirmationSummary, formatCRC, normalizeAmount, validateFinancialOpeningAmounts } from '../helpers/financial-opening';
import { useAuth } from '../hooks/auth-context';

type FormState = { openingDate: string; initialPortfolio: string; initialUncollectibleAmount: string; initialAvailableAmount: string; historicalSeedCapital: string; observations: string };
const initialForm: FormState = { openingDate: '', initialPortfolio: '', initialUncollectibleAmount: '', initialAvailableAmount: '', historicalSeedCapital: '', observations: '' };
export function FinancialOpeningPage(): ReactElement {
  const { can } = useAuth(); const [state, setState] = useState<FinancialOpeningResponse | null>(null); const [form, setForm] = useState<FormState>(initialForm); const [confirming, setConfirming] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = async () => { try { setState(await financialOpeningUseCases.get.execute()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible cargar la apertura financiera.'); } };
  useEffect(() => { void load(); }, []);
  const update = (field: keyof FormState, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async () => { const errors = validateFinancialOpeningAmounts(form); if (!form.openingDate) errors.push('La fecha de apertura es requerida.'); if (errors.length) { setError(errors[0]); setConfirming(false); return; } setSaving(true); setError(null); try { const opening = await financialOpeningUseCases.perform.execute({ ...form, initialPortfolio: normalizeAmount(form.initialPortfolio), initialUncollectibleAmount: normalizeAmount(form.initialUncollectibleAmount), initialAvailableAmount: normalizeAmount(form.initialAvailableAmount), historicalSeedCapital: normalizeAmount(form.historicalSeedCapital), observations: form.observations.trim() || null }); setState({ configured: true, opening }); setConfirming(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible realizar la apertura financiera.'); } finally { setSaving(false); } };
  if (error && !state) return <section className="payment-page"><div className="catalog-message catalog-message--error" role="alert">{error}</div></section>;
  return <section className="payment-page" aria-labelledby="financial-opening-title"><div className="payment-heading"><div><h2 id="financial-opening-title">Configuración financiera</h2><p>Define el punto de partida para el control financiero del negocio.</p></div></div>{error && <div className="catalog-message catalog-message--error" role="alert">{error}</div>}{state?.configured && state.opening ? <ReadOnlyOpening opening={state.opening} /> : <form className="financial-opening-form" onSubmit={(event) => { event.preventDefault(); if (canPerformOpening(can)) setConfirming(true); }}><div className="opening-section"><h3>Fecha de apertura</h3><label>Fecha<input type="date" value={form.openingDate} onChange={(event) => update('openingDate', event.target.value)} /></label></div><div className="opening-section"><h3>Cartera inicial</h3><label>Importe<input inputMode="decimal" value={form.initialPortfolio} onChange={(event) => update('initialPortfolio', event.target.value)} /></label></div><div className="opening-section"><h3>Capital incobrable inicial</h3><label>Importe<input inputMode="decimal" value={form.initialUncollectibleAmount} onChange={(event) => update('initialUncollectibleAmount', event.target.value)} /></label></div><div className="opening-grid"><div className="opening-section"><h3>Importe disponible</h3><label>Importe<input inputMode="decimal" value={form.initialAvailableAmount} onChange={(event) => update('initialAvailableAmount', event.target.value)} /></label></div><div className="opening-section"><h3>Capital semilla histórico</h3><label>Importe<input inputMode="decimal" value={form.historicalSeedCapital} onChange={(event) => update('historicalSeedCapital', event.target.value)} /></label></div></div><div className="opening-section"><h3>Observaciones</h3><label>Opcional<textarea value={form.observations} onChange={(event) => update('observations', event.target.value)} /></label></div>{canPerformOpening(can) && <button className="button button--primary" type="submit">Realizar apertura</button>}{!canPerformOpening(can) && <p className="permission-hint">No tienes permiso para realizar la apertura financiera.</p>}</form>}{confirming && <ConfirmationDialog form={form} saving={saving} onCancel={() => setConfirming(false)} onConfirm={() => void submit()} />}</section>;
}
function ReadOnlyOpening({ opening }: { opening: FinancialOpening }): ReactElement { return <div className="opening-readonly"><span className="status-badge status-badge--active">APERTURA FINANCIERA REALIZADA</span><dl className="opening-values">{[['Fecha de apertura', opening.openingDate], ['Cartera inicial', formatCRC(opening.initialPortfolio)], ['Capital incobrable inicial', formatCRC(opening.initialUncollectibleAmount)], ['Importe disponible', formatCRC(opening.initialAvailableAmount)], ['Capital semilla histórico', formatCRC(opening.historicalSeedCapital)], ['Realizada por', opening.openedBy.fullName], ['Realizada el', new Date(opening.openedAt).toLocaleString('es-CR')]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{opening.observations && <p><strong>Observaciones:</strong> {opening.observations}</p>}</div>; }
function ConfirmationDialog({ form, saving, onCancel, onConfirm }: { form: FormState; saving: boolean; onCancel: () => void; onConfirm: () => void }): ReactElement { return <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="opening-confirm-title"><h3 id="opening-confirm-title">Realizar apertura financiera</h3><p>Verifica los valores. Esta apertura no puede editarse directamente.</p><dl className="opening-summary">{financialOpeningConfirmationSummary(form).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{label === 'Fecha de apertura' ? value : formatCRC(value)}</dd></div>)}</dl><div className="dialog-actions"><button className="button button--secondary" type="button" onClick={onCancel}>Cancelar</button><button className="button button--primary" type="button" disabled={saving} onClick={onConfirm}>Confirmar apertura</button></div></div></div>; }
