import { useEffect, useMemo, useState, type ReactElement } from 'react';
import { customerUseCases } from '../../app/customers';
import { territorialUseCases } from '../../app/territorial';
import type { Canton, District, Province } from '../../domain/entities/territorial';
import type { CustomerForm } from '../../domain/entities/customer';
import { CompactImageUploader } from '../components/CompactImageUploader';
import { normalizeCustomerPatch } from '../../application/use-cases/customer-normalization';
import { formatNationality, nationalityLabels, type Nationality } from '../formatters/nationality';
const initial: CustomerForm = { identificationType: 'NATIONAL', identification: '', firstName: '', middleName: '', firstLastName: '', secondLastName: '', gender: '', birthDate: '', primaryPhone: '', secondaryPhone: '', email: '', nationality: '', otherNationality: '', provinceCode: '', cantonCode: '', districtCode: '', exactAddress: '', latitude: '', longitude: '', observations: '' };
const emptyFileError = (file?: File): string => file && (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) ? 'El archivo debe ser JPEG, PNG o WEBP y pesar máximo 5 MB.' : '';
export function NewCustomerPage(): ReactElement {
  const [form, setForm] = useState<CustomerForm>(initial); const [step, setStep] = useState(1); const [provinces, setProvinces] = useState<Province[]>([]); const [cantons, setCantons] = useState<Canton[]>([]); const [districts, setDistricts] = useState<District[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState<{ name: string; identification: string }>();
  const update = (patch: Partial<CustomerForm>) => setForm((current) => ({ ...current, ...normalizeCustomerPatch(patch, current.identificationType) }));
  useEffect(() => { void territorialUseCases.listProvinces.execute().then(setProvinces).catch(() => setError('No se pudieron cargar las provincias.')); }, []);
  useEffect(() => { if (!form.provinceCode) { setCantons([]); return; } void territorialUseCases.listCantons.execute(Number(form.provinceCode)).then(setCantons).catch(() => setError('No se pudieron cargar los cantones.')); }, [form.provinceCode]);
  useEffect(() => { if (!form.cantonCode) { setDistricts([]); return; } void territorialUseCases.listDistricts.execute({ cantonCode: Number(form.cantonCode) }).then(setDistricts).catch(() => setError('No se pudieron cargar los distritos.')); }, [form.cantonCode]);
  const selectedDistrict = useMemo(() => districts.find((item) => String(item.code) === form.districtCode), [districts, form.districtCode]);
  const coordinatesValid = form.latitude !== '' && form.longitude !== '' && Number.isFinite(Number(form.latitude)) && Number.isFinite(Number(form.longitude)) && Number(form.latitude) >= -90 && Number(form.latitude) <= 90 && Number(form.longitude) >= -180 && Number(form.longitude) <= 180;
  const validateStep = (target: number): string => { if (target === 2 && (!form.identification || !form.firstName.trim() || !form.firstLastName.trim() || !form.gender || !form.birthDate || !form.identificationFront)) return 'Completá los datos personales y la identificación.'; if (target === 3 && (!form.primaryPhone.trim() || !form.nationality || !form.districtCode || !form.exactAddress.trim())) return 'Completá el contacto y la dirección.'; if (emptyFileError(form.identificationFront) || emptyFileError(form.propertyPhoto)) return emptyFileError(form.identificationFront) || emptyFileError(form.propertyPhoto); return ''; };
  const save = async () => { const message = validateStep(3); if (message || (form.latitude !== '') !== (form.longitude !== '')) { setError(message || 'Indicá ambas coordenadas o dejá ambas vacías.'); return; } const lat = Number(form.latitude); const lng = Number(form.longitude); if ((form.latitude && (!Number.isFinite(lat) || lat < -90 || lat > 90)) || (form.longitude && (!Number.isFinite(lng) || lng < -180 || lng > 180))) { setError('Las coordenadas no son válidas.'); return; } setSaving(true); setError(''); try { const result = await customerUseCases.register.execute(form); setSuccess({ name: result.fullName, identification: result.identification }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible registrar el cliente.'); } finally { setSaving(false); } };
  if (success) return <section className="customer-wizard"><div className="success-message"><strong>Cliente registrado correctamente</strong><p>{success.name} · {success.identification}</p></div><button className="button button--primary" onClick={() => { setForm(initial); setStep(1); setSuccess(undefined); }}>Registrar otro cliente</button></section>;
  return <section className="customer-wizard"><div className="customer-heading"><div><h2>Nuevo cliente</h2><p>Registro de nuevos clientes</p></div><span>Paso {step} de 3</span></div><div className="wizard-steps"><b className={step === 1 ? 'active' : ''}>Datos personales</b><b className={step === 2 ? 'active' : ''}>Contacto y dirección</b><b className={step === 3 ? 'active' : ''}>Ubicación y documentación</b></div>{error && <p className="form-error">{error}</p>}<div className="customer-form">
    {step === 1 && <><fieldset><legend>Tipo de identificación</legend><label><input type="radio" checked={form.identificationType === 'NATIONAL'} onChange={() => update({ identificationType: 'NATIONAL', identification: '' })} /> Nacional</label><label><input type="radio" checked={form.identificationType === 'FOREIGN'} onChange={() => update({ identificationType: 'FOREIGN', identification: '' })} /> Extranjero</label></fieldset><label>Identificación<input value={form.identification} onChange={(event) => update({ identification: form.identificationType === 'NATIONAL' ? event.target.value.replace(/\D/g, '').slice(0, 9).replace(/(\d)(\d{4})(\d{4})/, '$1-$2-$3') : event.target.value })} placeholder={form.identificationType === 'NATIONAL' ? '#-####-####' : 'Identificación'} /></label><div className="form-grid"><label>Nombre<input value={form.firstName} onChange={(e) => update({ firstName: e.target.value })} /></label><label>Segundo nombre<input value={form.middleName} onChange={(e) => update({ middleName: e.target.value })} /></label><label>Primer apellido<input value={form.firstLastName} onChange={(e) => update({ firstLastName: e.target.value })} /></label><label>Segundo apellido<input value={form.secondLastName} onChange={(e) => update({ secondLastName: e.target.value })} /></label><label>Género<select value={form.gender} onChange={(e) => update({ gender: e.target.value as CustomerForm['gender'] })}><option value="">Seleccionar</option><option value="MALE">Masculino</option><option value="FEMALE">Femenino</option></select></label><label>Fecha de nacimiento<input type="date" max={new Date().toISOString().slice(0, 10)} value={form.birthDate} onChange={(e) => update({ birthDate: e.target.value })} /></label></div><CompactImageUploader label="Identificación frontal" required file={form.identificationFront} onChange={(file) => update({ identificationFront: file })} /></>}
    {step === 2 && <><div className="form-grid"><label>Teléfono principal<input value={form.primaryPhone} onChange={(e) => update({ primaryPhone: e.target.value })} /></label><label>Teléfono secundario<input value={form.secondaryPhone} onChange={(e) => update({ secondaryPhone: e.target.value })} /></label><label>Correo electrónico<input type="email" value={form.email} onChange={(e) => update({ email: e.target.value })} /></label><label>Nacionalidad<select value={form.nationality} onChange={(e) => update({ nationality: e.target.value as CustomerForm['nationality'], otherNationality: '' })}><option value="">Seleccionar</option>{(Object.keys(nationalityLabels) as Nationality[]).map((nationality) => <option key={nationality} value={nationality}>{formatNationality(nationality)}</option>)}</select></label>{form.nationality === 'OTHER' && <label>Otra nacionalidad<input value={form.otherNationality} onChange={(e) => update({ otherNationality: e.target.value })} /></label>}</div><div className="form-grid"><label>Provincia<select value={form.provinceCode} onChange={(e) => update({ provinceCode: e.target.value, cantonCode: '', districtCode: '' })}><option value="">Seleccionar</option>{provinces.map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label>Cantón<select value={form.cantonCode} disabled={!form.provinceCode} onChange={(e) => update({ cantonCode: e.target.value, districtCode: '' })}><option value="">Seleccionar</option>{cantons.map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label>Distrito<select value={form.districtCode} disabled={!form.cantonCode} onChange={(e) => update({ districtCode: e.target.value })}><option value="">Seleccionar</option>{districts.map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></label></div><label>Dirección exacta<textarea value={form.exactAddress} onChange={(e) => update({ exactAddress: e.target.value })} /></label></>}
    {step === 3 && <><div className="location-actions"><button type="button" className="button button--secondary" onClick={() => navigator.geolocation?.getCurrentPosition((position) => update({ latitude: String(position.coords.latitude), longitude: String(position.coords.longitude) }), () => setError('No se pudo obtener la ubicación.'))}>Usar mi ubicación</button><span>{selectedDistrict ? `${selectedDistrict.province.name} · ${selectedDistrict.canton.name} · ${selectedDistrict.name}` : 'Sin distrito seleccionado'}</span></div><div className="form-grid"><label>Latitud<input type="number" step="any" value={form.latitude} onChange={(e) => update({ latitude: e.target.value })} /></label><label>Longitud<input type="number" step="any" value={form.longitude} onChange={(e) => update({ longitude: e.target.value })} /></label></div>{coordinatesValid && <p className="map-links"><a target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${form.latitude},${form.longitude}`)}`}>Google Maps</a><a target="_blank" rel="noopener noreferrer" href={`https://www.waze.com/ul?ll=${encodeURIComponent(`${form.latitude},${form.longitude}`)}&navigate=yes`}>Waze</a></p>}<CompactImageUploader label="Foto de casa o negocio" file={form.propertyPhoto} onChange={(file) => update({ propertyPhoto: file })} /><label>Observaciones<textarea value={form.observations} onChange={(e) => update({ observations: e.target.value })} /></label><p className="customer-summary"><strong>Resumen:</strong> {form.firstName} {form.firstLastName} · {form.identification || 'Sin identificación'} · Activo</p></>}
  </div><div className="wizard-actions">{step > 1 && <button className="button button--secondary" onClick={() => { setError(''); setStep(step - 1); }}>Atrás</button>}{step < 3 ? <button className="button button--primary" onClick={() => { const message = validateStep(step + 1); if (message) setError(message); else { setError(''); setStep(step + 1); } }}>Continuar</button> : <button className="button button--primary" disabled={saving} onClick={() => void save()}>{saving ? 'Guardando…' : 'Guardar cliente'}</button>}</div></section>;
}
