import { useEffect, useState, type ReactElement } from 'react';
import { security } from '../../app/security';
import type { RoleRecord, UserRecord } from '../../application/ports/security.repository';
import { useAuth } from '../hooks/auth-context';

type Modal = 'create' | 'edit' | 'role' | 'password' | 'status' | null;
type Form = { fullName: string; username: string; roleId: string; password: string; confirm: string };
const emptyForm: Form = { fullName: '', username: '', roleId: '', password: '', confirm: '' };

export function UsersPage(): ReactElement {
  const { can } = useAuth();
  const [items, setItems] = useState<UserRecord[]>([]); const [roles, setRoles] = useState<RoleRecord[]>([]);
  const [query, setQuery] = useState({ search: '', status: 'ALL' as 'ACTIVE' | 'INACTIVE' | 'ALL', roleId: '', page: 1, pageSize: 20 });
  const [total, setTotal] = useState(0); const [modal, setModal] = useState<Modal>(null); const [selected, setSelected] = useState<UserRecord>(); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); try { const result = await security.users.list(query); setItems(result.items); setTotal(result.total); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudieron cargar los usuarios.'); } finally { setLoading(false); } };
  useEffect(() => { void security.roles.list().then(setRoles).catch(() => setError('No se pudieron cargar los roles.')); }, []);
  useEffect(() => { void load(); }, [query.page, query.status, query.roleId]);
  const open = (kind: Modal, item?: UserRecord) => { setSelected(item); setModal(kind); setError(''); setForm(item ? { ...emptyForm, fullName: item.fullName, username: item.username, roleId: item.role.id } : { ...emptyForm, roleId: roles[0]?.id ?? '' }); };
  const save = async () => { if (modal === 'status' || !modal) return; if ((modal === 'create' && (!form.fullName.trim() || !form.username.trim() || !form.roleId)) || ((modal === 'create' || modal === 'password') && (form.password.length < 12 || form.password !== form.confirm))) { setError('Completá los datos y verificá una contraseña de 12 caracteres mínimo.'); return; } setBusy(true); try { if (modal === 'create') await security.users.create({ username: form.username, fullName: form.fullName, roleId: form.roleId, password: form.password }); else if (modal === 'edit' && selected) await security.users.update(selected.id, { username: form.username, fullName: form.fullName }); else if (modal === 'role' && selected) await security.users.role(selected.id, form.roleId); else if (modal === 'password' && selected) await security.users.reset(selected.id, form.password); setModal(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar.'); } finally { setBusy(false); } };
  const toggleStatus = async () => { if (!selected) return; setBusy(true); try { await security.users.status(selected.id, !selected.isActive); setModal(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible cambiar el estado.'); } finally { setBusy(false); } };
  return <section className="security-page"><div className="payment-heading"><div><p className="eyebrow">SEGURIDAD</p><h2>Usuarios</h2><p>Administra las cuentas y sus accesos.</p></div>{can('users.create') && <button className="button button--primary" onClick={() => open('create')}>Nuevo usuario</button>}</div><div className="payment-toolbar"><label>Buscar<input value={query.search} onChange={(e) => setQuery({ ...query, search: e.target.value, page: 1 })} placeholder="Nombre o usuario" /></label><label>Estado<select value={query.status} onChange={(e) => setQuery({ ...query, status: e.target.value as typeof query.status, page: 1 })}><option value="ALL">Todos</option><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option></select></label><label>Rol<select value={query.roleId} onChange={(e) => setQuery({ ...query, roleId: e.target.value, page: 1 })}><option value="">Todos</option>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><button className="button button--secondary" onClick={() => void load()}>Buscar</button></div>{error && <div className="catalog-message catalog-message--error" role="alert">{error}</div>}{loading ? <div className="catalog-message">Cargando usuarios…</div> : <UserTable items={items} can={can} open={open} />}{<div className="security-pagination"><button className="button button--secondary" disabled={query.page <= 1} onClick={() => setQuery({ ...query, page: query.page - 1 })}>Anterior</button><span>Página {query.page} · {total} usuarios</span><button className="button button--secondary" disabled={query.page * query.pageSize >= total} onClick={() => setQuery({ ...query, page: query.page + 1 })}>Siguiente</button></div>}{modal && <UserDialog modal={modal} selected={selected} roles={roles} form={form} setForm={setForm} busy={busy} close={() => setModal(null)} save={() => void (modal === 'status' ? toggleStatus() : save())} />}</section>;
}

function UserTable({ items, can, open }: { items: UserRecord[]; can: (code: string) => boolean; open: (modal: Modal, item?: UserRecord) => void }): ReactElement { return <div className="catalog-table-wrap"><table className="catalog-table users-table"><thead><tr><th>Nombre</th><th>Usuario</th><th>Rol</th><th>Último acceso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.fullName}</td><td>{item.username}</td><td>{item.role.name}</td><td>{item.lastLoginAt ? new Date(item.lastLoginAt).toLocaleString() : 'Nunca'}</td><td><span className={`status-badge ${item.isActive ? 'status-badge--active' : 'status-badge--inactive'}`}>{item.isActive ? 'Activo' : 'Inactivo'}</span></td><td><div className="row-actions">{can('users.update') && <button onClick={() => open('edit', item)}>Editar</button>}{can('users.role.assign') && <button onClick={() => open('role', item)}>Rol</button>}{can('users.password.reset') && <button onClick={() => open('password', item)}>Restablecer</button>}{can('users.status.change') && <button onClick={() => open('status', item)}>{item.isActive ? 'Inactivar' : 'Activar'}</button>}</div></td></tr>)}</tbody></table></div>; }
function UserDialog({ modal, selected, roles, form, setForm, busy, close, save }: { modal: Exclude<Modal, null>; selected?: UserRecord; roles: RoleRecord[]; form: Form; setForm: (form: Form) => void; busy: boolean; close: () => void; save: () => void }): ReactElement {
  const status = modal === 'status';
  return <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true"><h3>{modal === 'create' ? 'Nuevo usuario' : modal === 'edit' ? 'Editar usuario' : modal === 'role' ? 'Asignar rol' : modal === 'password' ? 'Restablecer contraseña' : `${selected?.isActive ? 'Inactivar' : 'Activar'} usuario`}</h3>
    {status ? <p>¿Confirmás cambiar el estado de <strong>{selected?.fullName}</strong>?</p> : <div>
      {(modal === 'create' || modal === 'edit') && <><label>Nombre completo<input value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} /></label><label>Usuario<input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></label></>}
      {(modal === 'create' || modal === 'role') && <label>Rol<select value={form.roleId} onChange={(e) => setForm({ ...form, roleId: e.target.value })}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label>}
      {(modal === 'create' || modal === 'password') && <><label>Contraseña<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label>Confirmar contraseña<input type="password" value={form.confirm} onChange={(e) => setForm({ ...form, confirm: e.target.value })} /></label></>}
    </div>}
    <div className="dialog-actions"><button className="button button--secondary" onClick={close}>Cancelar</button><button className="button button--primary" disabled={busy} onClick={save}>{busy ? 'Guardando…' : 'Confirmar'}</button></div>
  </div></div>;
}
