import { createHash } from 'crypto';
import { CashMovementConflictError, CashMovementNotFoundError, CashMovementValidationError } from '../../domain/cash-movement/cash-movement.errors';
import { MANUAL_CASH_MOVEMENT_CONCEPTS, type CashMovement, type CashMovementConcept, type CashMovementDirection } from '../../domain/cash-movement/cash-movement.types';
import type { CashMovementFilters, CashMovementRepository, CreateCashMovement } from './cash-movement.repository';

const DATE = /^\d{4}-\d{2}-\d{2}$/;
const MONEY = /^(?:0|[1-9]\d{0,15})(?:\.\d{1,2})?$/;
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: string) => `${value.split('.')[0]}.${(value.split('.')[1] ?? '').padEnd(2, '0')}`;
const isStrictIsoDate = (value: string): boolean => { if (!DATE.test(value)) return false; const parsed = new Date(`${value}T00:00:00Z`); return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value; };
export function directionForManualConcept(concept: CashMovementConcept): CashMovementDirection { if (concept === 'CAPITAL_CONTRIBUTION' || concept === 'EXTERNAL_INCOME') return 'INFLOW'; if (concept === 'CAPITAL_WITHDRAWAL' || concept === 'OPERATING_EXPENSE') return 'OUTFLOW'; throw new CashMovementValidationError('El concepto no está disponible para movimientos manuales.'); }
export function fingerprint(input: Omit<CreateCashMovement, 'idempotencyFingerprint' | 'idempotencyKey' | 'createdByUserId'>): string { return createHash('sha256').update(JSON.stringify([input.direction, input.concept, input.amount, input.movementDate, input.paymentMethodId, input.observations ?? null])).digest('hex'); }
function validate(input: Omit<CreateCashMovement, 'createdByUserId' | 'idempotencyFingerprint'>, openingDate: string | null, originalDate?: string): Omit<CreateCashMovement, 'createdByUserId' | 'idempotencyFingerprint'> { if (!isStrictIsoDate(input.movementDate) || input.movementDate > today() || (openingDate && input.movementDate < openingDate) || (originalDate && input.movementDate < originalDate)) throw new CashMovementValidationError('La fecha del movimiento no es válida.'); if (!MONEY.test(input.amount) || Number(input.amount) <= 0) throw new CashMovementValidationError('El importe debe ser mayor que cero y tener hasta 2 decimales.'); if (!input.paymentMethodId?.trim()) throw new CashMovementValidationError('La forma de pago es requerida.'); return { ...input, amount: money(input.amount), observations: input.observations?.trim().toUpperCase() || null };
}
export class ListCashMovementsUseCase { constructor(private readonly repository: CashMovementRepository) {} execute(filters: CashMovementFilters) { return this.repository.list(filters); } }
export class SummarizeCashMovementsUseCase { constructor(private readonly repository: CashMovementRepository) {} execute(filters: Pick<CashMovementFilters, 'fromDate' | 'toDate' | 'direction' | 'concept' | 'paymentMethodId' | 'search'>) { return this.repository.summary(filters); } }
export class RecordManualCashMovementUseCase { constructor(private readonly repository: CashMovementRepository, private readonly opening: { find(): Promise<{ openingDate: string } | null> }, private readonly paymentMethods: { findById(id: string): Promise<{ isActive: boolean } | null> }) {} async execute(input: { concept: CashMovementConcept; amount: string; movementDate: string; paymentMethodId: string; observations?: string | null; idempotencyKey?: string | null }, actorId: string): Promise<CashMovement> { if (!MANUAL_CASH_MOVEMENT_CONCEPTS.includes(input.concept as never)) throw new CashMovementValidationError('El concepto no está disponible para movimientos manuales.'); const opening = await this.opening.find(); if (!opening) throw new CashMovementConflictError('Debe realizar la apertura financiera antes de registrar movimientos.'); const method = await this.paymentMethods.findById(input.paymentMethodId); if (!method || !method.isActive) throw new CashMovementValidationError('La forma de pago no existe o está inactiva.'); const base = validate({ ...input, direction: directionForManualConcept(input.concept), observations: input.observations ?? null }, opening.openingDate); const key = input.idempotencyKey?.trim() || null; const fp = fingerprint(base); if (key) { const existing = await this.repository.findByIdempotencyKey(key); if (existing) { if (existing.idempotencyFingerprint !== fp) throw new CashMovementConflictError('La clave de idempotencia ya fue utilizada con otros datos.'); return existing; } } try { return await this.repository.create({ ...base, createdByUserId: actorId, idempotencyKey: key, idempotencyFingerprint: fp }); } catch (error) { if (key && (error as { code?: string }).code === '23505') { const existing = await this.repository.findByIdempotencyKey(key); if (existing?.idempotencyFingerprint === fp) return existing; throw new CashMovementConflictError('La clave de idempotencia ya fue utilizada con otros datos.'); } throw error; } } }
export class ReverseCashMovementUseCase { constructor(private readonly repository: CashMovementRepository, private readonly opening: { find(): Promise<{ openingDate: string } | null> }) {} async execute(id: string, input: { movementDate: string; reason: string }, actorId: string): Promise<CashMovement> { const original = await this.repository.findById(id); if (!original) throw new CashMovementNotFoundError('El movimiento no existe.'); if (!MANUAL_CASH_MOVEMENT_CONCEPTS.includes(original.concept as never)) throw new CashMovementValidationError('Solo se pueden reversar movimientos manuales.'); const opening = await this.opening.find(); if (!opening) throw new CashMovementConflictError('Debe realizar la apertura financiera antes de registrar movimientos.'); if (!input.reason?.trim()) throw new CashMovementValidationError('La razón de reversión es requerida.'); const base = validate({ direction: original.direction === 'INFLOW' ? 'OUTFLOW' : 'INFLOW', concept: 'REVERSAL', amount: original.amount, movementDate: input.movementDate, paymentMethodId: original.paymentMethodId, observations: input.reason }, opening.openingDate, original.movementDate); return this.repository.reverse(original, { ...base, createdByUserId: actorId, reversedMovementId: original.id }); } }
export interface CashMovementRecorder { record(input: CreateCashMovement, actorId: string): Promise<CashMovement>; }
