import type { CustomerCreated, CustomerDetail, CustomerExportItem, CustomerForm, CustomerListItem, CustomerSummary } from '../../domain/entities/customer';
import type { AssignedCollector, AssignedCustomerQuery, AssignedCustomerResult, CustomerSite, SiteAuthorization, SiteUpdateScope } from '../../domain/entities/customer-site';
import type { CustomerFinancialAnalysis } from '../../domain/entities/customer-financial-analysis';
export type CustomerStatusFilter = 'ACTIVE' | 'INACTIVE' | 'ALL';
export type CustomerSortBy = 'identification' | 'name' | 'phone' | 'address' | 'status';
export type CustomerSortOrder = 'asc' | 'desc';
export type CustomerListSort = { sortBy?: CustomerSortBy; sortOrder?: CustomerSortOrder };
export type CustomerListResult = { items: CustomerListItem[]; total: number; page: number; pageSize: number; totalPages: number };
export type CustomerSummaryQuery = { search: string; status: CustomerStatusFilter };
export interface CustomerRepository { create(input: CustomerForm): Promise<CustomerCreated>; list(query: CustomerSummaryQuery & { page: number; pageSize: number } & CustomerListSort): Promise<CustomerListResult>; exportAll(): Promise<CustomerExportItem[]>; assigned(query: AssignedCustomerQuery): Promise<AssignedCustomerResult>; summary(query: CustomerSummaryQuery): Promise<CustomerSummary>; detail(id: string): Promise<CustomerDetail>; financialAnalysis(id: string, asOf: string): Promise<CustomerFinancialAnalysis>; site(id: string): Promise<CustomerSite>; sitePhoto(id: string): Promise<Blob>; assignedCollectors(id: string): Promise<AssignedCollector[]>; updateSite(id: string, input: { latitude?: number; longitude?: number; propertyPhoto?: File }): Promise<CustomerSite>; listAuthorizations(id: string): Promise<SiteAuthorization[]>; authorizeSiteUpdate(id: string, input: { collectorUserId: string; scope: SiteUpdateScope; reason: string; expiresAt: string }): Promise<SiteAuthorization>; revokeSiteAuthorization(id: string, authorizationId: string): Promise<void>; update(id: string, input: Partial<CustomerForm>): Promise<CustomerDetail>; changeStatus(id: string, isActive: boolean): Promise<CustomerCreated>; file(id: string, kind: 'identification' | 'property'): Promise<Blob>; }
