import { MigrationInterface, QueryRunner } from 'typeorm';
export class CustomerSiteSecurity1760800000000 implements MigrationInterface {
  name = 'CustomerSiteSecurity1760800000000';
  async up(q: QueryRunner): Promise<void> {
    await q.query('ALTER TABLE "customer_addresses" ADD "site_data_updated_by_user_id" uuid NULL, ADD "site_data_updated_at" timestamptz NULL');
    await q.query('ALTER TABLE "customer_addresses" ADD CONSTRAINT "FK_customer_addresses_site_updated_by" FOREIGN KEY ("site_data_updated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL');
    await q.query('CREATE TABLE "customer_route_assignments" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "customer_id" uuid NOT NULL, "route_id" uuid NOT NULL, "assigned_by_user_id" uuid NOT NULL, "assigned_at" timestamptz NOT NULL DEFAULT now(), "ended_at" timestamptz NULL, CONSTRAINT "PK_customer_route_assignments" PRIMARY KEY ("id"), CONSTRAINT "FK_cra_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT, CONSTRAINT "FK_cra_route" FOREIGN KEY ("route_id") REFERENCES "routes"("id") ON DELETE RESTRICT, CONSTRAINT "FK_cra_assigned_by" FOREIGN KEY ("assigned_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)');
    await q.query('CREATE TABLE "collector_route_assignments" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "collector_user_id" uuid NOT NULL, "route_id" uuid NOT NULL, "assigned_by_user_id" uuid NOT NULL, "assigned_at" timestamptz NOT NULL DEFAULT now(), "ended_at" timestamptz NULL, CONSTRAINT "PK_collector_route_assignments" PRIMARY KEY ("id"), CONSTRAINT "FK_cola_user" FOREIGN KEY ("collector_user_id") REFERENCES "users"("id") ON DELETE RESTRICT, CONSTRAINT "FK_cola_route" FOREIGN KEY ("route_id") REFERENCES "routes"("id") ON DELETE RESTRICT, CONSTRAINT "FK_cola_assigned_by" FOREIGN KEY ("assigned_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)');
    await q.query('CREATE INDEX "idx_cra_active_customer" ON "customer_route_assignments" ("customer_id") WHERE "ended_at" IS NULL'); await q.query('CREATE INDEX "idx_cola_active_collector" ON "collector_route_assignments" ("collector_user_id") WHERE "ended_at" IS NULL');
    await q.query(`CREATE TABLE "customer_site_update_authorizations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "customer_id" uuid NOT NULL, "collector_user_id" uuid NOT NULL, "scope" varchar NOT NULL, "reason" text NOT NULL, "authorized_by_user_id" uuid NOT NULL, "authorized_at" timestamptz NOT NULL DEFAULT now(), "expires_at" timestamptz NOT NULL, "used_at" timestamptz NULL, "revoked_at" timestamptz NULL, CONSTRAINT "PK_customer_site_auth" PRIMARY KEY ("id"), CONSTRAINT "CHK_customer_site_auth_scope" CHECK ("scope" IN ('LOCATION','PHOTO','LOCATION_AND_PHOTO')), CONSTRAINT "CHK_customer_site_auth_reason" CHECK (btrim("reason") <> ''), CONSTRAINT "FK_site_auth_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT, CONSTRAINT "FK_site_auth_collector" FOREIGN KEY ("collector_user_id") REFERENCES "users"("id") ON DELETE RESTRICT, CONSTRAINT "FK_site_auth_authorizer" FOREIGN KEY ("authorized_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT)`);
    await q.query('CREATE INDEX "idx_site_auth_customer" ON "customer_site_update_authorizations" ("customer_id", "authorized_at")');
  }
  async down(q: QueryRunner): Promise<void> { await q.query('DROP TABLE "customer_site_update_authorizations"'); await q.query('DROP INDEX "idx_cola_active_collector"'); await q.query('DROP INDEX "idx_cra_active_customer"'); await q.query('DROP TABLE "collector_route_assignments"'); await q.query('DROP TABLE "customer_route_assignments"'); await q.query('ALTER TABLE "customer_addresses" DROP CONSTRAINT "FK_customer_addresses_site_updated_by"'); await q.query('ALTER TABLE "customer_addresses" DROP COLUMN "site_data_updated_at", DROP COLUMN "site_data_updated_by_user_id"'); }
}
