import { MigrationInterface, QueryRunner } from 'typeorm';
export class CreateCustomers1760500000000 implements MigrationInterface {
  name = 'CreateCustomers1760500000000';
  async up(q: QueryRunner): Promise<void> {
    await q.query('CREATE EXTENSION IF NOT EXISTS "pgcrypto"');
    await q.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "identification_type" varchar NOT NULL, "identification" varchar NOT NULL, "first_name" varchar NOT NULL, "middle_name" varchar, "first_last_name" varchar NOT NULL, "second_last_name" varchar, "gender" varchar NOT NULL, "birth_date" date NOT NULL, "primary_phone" varchar NOT NULL, "secondary_phone" varchar, "email" varchar, "nationality" varchar NOT NULL, "other_nationality" varchar, "identification_front_file_key" varchar NOT NULL, "observations" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_customers_id" PRIMARY KEY ("id"), CONSTRAINT "CHK_customers_identification_type" CHECK ("identification_type" IN ('NATIONAL','FOREIGN')), CONSTRAINT "CHK_customers_gender" CHECK ("gender" IN ('MALE','FEMALE')), CONSTRAINT "CHK_customers_nationality" CHECK ("nationality" IN ('COSTA_RICAN','NICARAGUAN','PANAMANIAN','HONDURAN','OTHER')), CONSTRAINT "CHK_customers_nonblank" CHECK (btrim("identification") <> '' AND btrim("first_name") <> '' AND btrim("first_last_name") <> '' AND btrim("primary_phone") <> '' AND btrim("identification_front_file_key") <> ''), CONSTRAINT "CHK_customers_other_nationality" CHECK (("nationality" = 'OTHER' AND btrim(coalesce("other_nationality",'')) <> '') OR ("nationality" <> 'OTHER' AND "other_nationality" IS NULL)))`);
    await q.query('CREATE UNIQUE INDEX "UQ_customers_identification_lower" ON "customers" (lower("identification"))');
    await q.query(`CREATE TABLE "customer_addresses" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "customer_id" uuid NOT NULL, "district_code" integer NOT NULL, "exact_address" text NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "property_photo_file_key" varchar, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_customer_addresses_id" PRIMARY KEY ("id"), CONSTRAINT "UQ_customer_addresses_customer_id" UNIQUE ("customer_id"), CONSTRAINT "CHK_customer_addresses_nonblank" CHECK (btrim("exact_address") <> ''), CONSTRAINT "CHK_customer_addresses_coordinates_pair" CHECK (("latitude" IS NULL AND "longitude" IS NULL) OR ("latitude" IS NOT NULL AND "longitude" IS NOT NULL)), CONSTRAINT "CHK_customer_addresses_latitude" CHECK ("latitude" IS NULL OR "latitude" BETWEEN -90 AND 90), CONSTRAINT "CHK_customer_addresses_longitude" CHECK ("longitude" IS NULL OR "longitude" BETWEEN -180 AND 180), CONSTRAINT "FK_customer_addresses_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT, CONSTRAINT "FK_customer_addresses_district" FOREIGN KEY ("district_code") REFERENCES "districts"("code") ON DELETE RESTRICT)`);
    await q.query('CREATE INDEX "idx_customer_addresses_district_code" ON "customer_addresses" ("district_code")');
  }
  async down(q: QueryRunner): Promise<void> { await q.query('DROP INDEX "idx_customer_addresses_district_code"'); await q.query('DROP TABLE "customer_addresses"'); await q.query('DROP INDEX "UQ_customers_identification_lower"'); await q.query('DROP TABLE "customers"'); }
}
