import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateLoans1761300000000 implements MigrationInterface {
  name = 'CreateLoans1761300000000';

  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE SEQUENCE "loan_number_seq" AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE`);
    await q.query(`CREATE TABLE "loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loan_number" bigint NOT NULL DEFAULT nextval('loan_number_seq'), "customer_id" uuid NOT NULL, "payment_frequency_id" uuid NOT NULL, "preferred_payment_method_id" uuid NOT NULL, "start_date" date NOT NULL, "principal" numeric(18,2) NOT NULL, "interest_amount" numeric(18,2) NOT NULL, "total_amount" numeric(18,2) NOT NULL, "observations" text, "status" varchar NOT NULL DEFAULT 'ACTIVE', "created_by_user_id" uuid NOT NULL, "idempotency_key" varchar(128), "idempotency_fingerprint" text, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_loans" PRIMARY KEY ("id"), CONSTRAINT "UQ_loans_number" UNIQUE ("loan_number"), CONSTRAINT "UQ_loans_idempotency" UNIQUE ("idempotency_key"), CONSTRAINT "CHK_loans_status" CHECK ("status" IN ('ACTIVE','CANCELLED','REFINANCED','UNCOLLECTIBLE','ANNULLED')), CONSTRAINT "CHK_loans_money" CHECK ("principal" > 0 AND "interest_amount" >= 0 AND "total_amount" = "principal" + "interest_amount"))`);
    await q.query(`CREATE TABLE "loan_disbursements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loan_id" uuid NOT NULL, "amount" numeric(18,2) NOT NULL, "payment_method_id" uuid NOT NULL, "disbursement_date" date NOT NULL, "created_by_user_id" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_loan_disbursements" PRIMARY KEY ("id"), CONSTRAINT "UQ_loan_disbursement_loan" UNIQUE ("loan_id"), CONSTRAINT "CHK_loan_disbursement_amount" CHECK ("amount" > 0))`);
    await q.query(`CREATE TABLE "payment_plan_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loan_id" uuid NOT NULL, "sequence" integer NOT NULL, "due_date" date NOT NULL, "pending_amount" numeric(18,2) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_payment_plan_entries" PRIMARY KEY ("id"), CONSTRAINT "UQ_payment_plan_sequence" UNIQUE ("loan_id","sequence"), CONSTRAINT "CHK_payment_plan_sequence" CHECK ("sequence" >= 1), CONSTRAINT "CHK_payment_plan_amount" CHECK ("pending_amount" > 0))`);
    await q.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_loans_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT, ADD CONSTRAINT "FK_loans_frequency" FOREIGN KEY ("payment_frequency_id") REFERENCES "payment_frequencies"("id") ON DELETE RESTRICT, ADD CONSTRAINT "FK_loans_preferred_method" FOREIGN KEY ("preferred_payment_method_id") REFERENCES "payment_methods"("id") ON DELETE RESTRICT, ADD CONSTRAINT "FK_loans_creator" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT`);
    await q.query(`ALTER TABLE "loan_disbursements" ADD CONSTRAINT "FK_disbursement_loan" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE RESTRICT, ADD CONSTRAINT "FK_disbursement_method" FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods"("id") ON DELETE RESTRICT, ADD CONSTRAINT "FK_disbursement_creator" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT`);
    await q.query(`ALTER TABLE "payment_plan_entries" ADD CONSTRAINT "FK_plan_loan" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE RESTRICT`);
    await q.query(`ALTER TABLE "cash_movements" ADD COLUMN "loan_disbursement_id" uuid, ADD CONSTRAINT "UQ_cash_loan_disbursement" UNIQUE ("loan_disbursement_id"), ADD CONSTRAINT "FK_cash_loan_disbursement" FOREIGN KEY ("loan_disbursement_id") REFERENCES "loan_disbursements"("id") ON DELETE RESTRICT, ADD CONSTRAINT "CHK_cash_loan_disbursement_pair" CHECK (("concept" = 'LOAN_DISBURSEMENT' AND "loan_disbursement_id" IS NOT NULL AND "direction" = 'OUTFLOW') OR ("concept" <> 'LOAN_DISBURSEMENT' AND "loan_disbursement_id" IS NULL))`);
    await q.query(`CREATE FUNCTION check_loan_disbursement_cash_pair() RETURNS trigger AS $fn$ DECLARE d_amount numeric(18,2); d_method uuid; d_date date; BEGIN IF NEW.loan_disbursement_id IS NOT NULL THEN SELECT amount, payment_method_id, disbursement_date INTO d_amount, d_method, d_date FROM loan_disbursements WHERE id = NEW.loan_disbursement_id; IF d_amount IS NULL OR NEW.amount <> d_amount OR NEW.payment_method_id <> d_method OR NEW.movement_date <> d_date THEN RAISE EXCEPTION 'Loan disbursement cash movement does not match its disbursement'; END IF; END IF; RETURN NEW; END; $fn$ LANGUAGE plpgsql`);
    await q.query(`CREATE TRIGGER trg_loan_disbursement_cash_pair BEFORE INSERT OR UPDATE ON cash_movements FOR EACH ROW EXECUTE FUNCTION check_loan_disbursement_cash_pair()`);
    await q.query(`CREATE INDEX "IDX_loans_start_date" ON "loans" ("start_date"); CREATE INDEX "IDX_loans_customer" ON "loans" ("customer_id"); CREATE INDEX "IDX_loans_frequency" ON "loans" ("payment_frequency_id"); CREATE INDEX "IDX_plan_loan_due" ON "payment_plan_entries" ("loan_id","due_date"); CREATE INDEX "IDX_plan_loan_pending" ON "payment_plan_entries" ("loan_id","pending_amount")`);
  }

  async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP TRIGGER "trg_loan_disbursement_cash_pair" ON "cash_movements"`); await q.query(`DROP FUNCTION "check_loan_disbursement_cash_pair"()`); await q.query(`ALTER TABLE "cash_movements" DROP CONSTRAINT "CHK_cash_loan_disbursement_pair", DROP CONSTRAINT "FK_cash_loan_disbursement", DROP CONSTRAINT "UQ_cash_loan_disbursement", DROP COLUMN "loan_disbursement_id"`);
    await q.query(`DROP TABLE "payment_plan_entries"`); await q.query(`DROP TABLE "loan_disbursements"`); await q.query(`DROP TABLE "loans"`); await q.query(`DROP SEQUENCE "loan_number_seq"`);
  }
}
