import { CurrentIdentity, SafeProfile, SafeUser, SecurityUser } from '../../domain/security/security.types';
import { PasswordHasher, SecureTokenGenerator, SecurityRepository } from './security.ports';
import { SecurityConflictError, SecurityNotFoundError, SecurityRateLimitError, SecurityUnauthorizedError, SecurityValidationError } from './security.errors';

const usernameOf = (value: string) => value.trim().toLowerCase();
const fullNameOf = (value: string) => value.trim().toUpperCase();
export const validatePassword = (value: string) => { if (typeof value !== 'string' || value.length < 12 || value.length > 128) throw new SecurityValidationError('La contraseña debe tener entre 12 y 128 caracteres.'); };
const safeUser = (user: SecurityUser): SafeUser => ({ id: user.id, username: user.username, fullName: user.fullName, role: { id: user.role.id, code: user.role.code, name: user.role.name, isSuperAdmin: user.role.isSuperAdmin }, isActive: user.isActive, lastLoginAt: user.lastLoginAt, createdAt: user.createdAt, updatedAt: user.updatedAt });
export class SecurityService {
  private readonly failures = new Map<string, { count: number; started: number }>();
  constructor(private readonly repository: SecurityRepository, private readonly hasher: PasswordHasher, private readonly tokens: SecureTokenGenerator, private readonly sessionTtlHours: number) {}
  async authenticate(rawToken?: string): Promise<CurrentIdentity> { if (!rawToken) throw new SecurityUnauthorizedError(); const session = await this.repository.findSessionByHash(this.tokens.hash(rawToken)); if (!session || session.revokedAt || session.expiresAt <= new Date()) throw new SecurityUnauthorizedError(); const user = await this.repository.findUserById(session.userId); if (!user || !user.isActive || !user.role.isActive) throw new SecurityUnauthorizedError(); return this.identity(user, session.id); }
  async login(input: string, password: string) { const username = usernameOf(input); const now = Date.now(); const previous = this.failures.get(username); if (previous && now - previous.started < 60000 && previous.count >= 5) throw new SecurityRateLimitError(); if (previous && now - previous.started >= 60000) this.failures.delete(username); const user = await this.repository.findUserByUsername(username); if (!user || !user.isActive || !user.role.isActive || !(await this.hasher.verify(user.passwordHash, password))) { const current = this.failures.get(username); this.failures.set(username, { count: (current?.count ?? 0) + 1, started: current?.started ?? now }); throw new SecurityUnauthorizedError(); } this.failures.delete(username); const generated = this.tokens.generate(); const session = await this.repository.saveSession({ userId: user.id, tokenHash: generated.hash, expiresAt: new Date(Date.now() + this.sessionTtlHours * 3600000), revokedAt: null }); await this.repository.saveUser({ id: user.id, lastLoginAt: new Date() }); return { token: generated.raw, identity: await this.identity({ ...user, lastLoginAt: new Date() }, session.id) }; }
  async logout(identity: CurrentIdentity) { await this.repository.revokeSession(identity.sessionId); }
  async changePassword(identity: CurrentIdentity, current: string, next: string) { validatePassword(next); const user = await this.repository.findUserById(identity.id); if (!user || !(await this.hasher.verify(user.passwordHash, current))) throw new SecurityUnauthorizedError(); await this.repository.saveUser({ id: user.id, passwordHash: await this.hasher.hash(next) }); await this.repository.revokeOtherSessions(user.id, identity.sessionId); }
  profile(identity: CurrentIdentity): SafeProfile { return { id: identity.id, username: identity.username, fullName: identity.fullName, role: identity.role, permissions: identity.role.isSuperAdmin ? [] : identity.permissions }; }
  async listUsers(filter: { search?: string; status?: string; roleId?: string; page: number; pageSize: number }) { const result = await this.repository.listUsers(filter); return { items: result.items.map(safeUser), page: filter.page, pageSize: filter.pageSize, total: result.total }; }
  async getUser(id: string) { const user = await this.repository.findUserById(id); if (!user) throw new SecurityNotFoundError(); return safeUser(user); }
  async createUser(input: { username: string; fullName: string; roleId: string; password: string }, actor: CurrentIdentity) { validatePassword(input.password); const role = await this.repository.findActiveRole(input.roleId); if (!role || (role.isSuperAdmin && !actor.role.isSuperAdmin)) throw new SecurityValidationError('El rol activo no es válido.'); if (await this.repository.usernameExists(input.username)) throw new SecurityConflictError(); return safeUser(await this.repository.saveUser({ username: usernameOf(input.username), fullName: fullNameOf(input.fullName), roleId: role.id, passwordHash: await this.hasher.hash(input.password), isActive: true, lastLoginAt: null })); }
  async updateUser(id: string, input: { username?: string; fullName?: string }) { const user = await this.repository.findUserById(id); if (!user) throw new SecurityNotFoundError(); if (input.username !== undefined) { if (await this.repository.usernameExists(input.username, id)) throw new SecurityConflictError(); user.username = usernameOf(input.username); } if (input.fullName !== undefined) user.fullName = fullNameOf(input.fullName); return safeUser(await this.repository.saveUser(user)); }
  async changeUserStatus(id: string, active: boolean) { const user = await this.repository.findUserById(id); if (!user) throw new SecurityNotFoundError(); if (!active && user.role.isSuperAdmin && await this.repository.countActiveSuperAdmins() <= 1) throw new SecurityValidationError('No se puede desactivar el último superadministrador activo.'); user.isActive = active; const saved = await this.repository.saveUser(user); if (!active) await this.repository.revokeUserSessions(id); return safeUser(saved); }
  async assignRole(id: string, roleId: string, actor: CurrentIdentity) { const user = await this.repository.findUserById(id); const role = await this.repository.findActiveRole(roleId); if (!user || !role || (role.isSuperAdmin && !actor.role.isSuperAdmin)) throw new SecurityValidationError('El rol activo no es válido.'); if (user.role.isSuperAdmin && !role.isSuperAdmin && await this.repository.countActiveSuperAdmins() <= 1) throw new SecurityValidationError('No se puede demover el último superadministrador activo.'); user.roleId = role.id; const saved = await this.repository.saveUser(user); await this.repository.revokeUserSessions(id); return safeUser(saved); }
  async resetPassword(id: string, password: string) { validatePassword(password); const user = await this.repository.findUserById(id); if (!user) throw new SecurityNotFoundError(); await this.repository.saveUser({ id, passwordHash: await this.hasher.hash(password) }); await this.repository.revokeUserSessions(id); }
  async roles() { return this.repository.listRoles(); } async permissions() { return this.repository.listPermissions(); }
  async rolePermissions(id: string) { const role = (await this.repository.listRoles()).find((item) => item.id === id); if (!role) throw new SecurityNotFoundError(); return { role, permissionCodes: await this.repository.rolePermissionCodes(id) }; }
  async replaceRolePermissions(id: string, codes: string[]) { const role = (await this.repository.listRoles()).find((item) => item.id === id); if (!role) throw new SecurityNotFoundError(); if (role.isSuperAdmin || role.code === 'ADMIN') throw new SecurityValidationError('La matriz del rol ADMIN está protegida.'); const permissions = await this.repository.findPermissionsByCodes([...new Set(codes)]); if (permissions.length !== new Set(codes).size) throw new SecurityValidationError('Código de permiso desconocido.'); await this.repository.replaceRolePermissions(id, permissions.map((permission) => permission.id)); return { success: true, permissionCodes: permissions.map((permission) => permission.code) }; }
  private async identity(user: SecurityUser, sessionId: string): Promise<CurrentIdentity> { return { id: user.id, username: user.username, fullName: user.fullName, role: { id: user.role.id, code: user.role.code, name: user.role.name, isSuperAdmin: user.role.isSuperAdmin }, permissions: await this.repository.rolePermissionCodes(user.roleId), sessionId }; }
}
